"""Add user_login_attempts table

Revision ID: c7f89123456b
Revises: ebb5a7ea1722
Create Date: 2026-08-08 19:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f89123456b'
down_revision = 'ebb5a7ea1722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login_attempts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('failed_attempts', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('first_failed_at', sa.DateTime(), nullable=True),
        sa.Column('last_failed_at', sa.DateTime(), nullable=True),
        sa.Column('blocked_at', sa.DateTime(), nullable=True),
        sa.Column('blocked_until', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_login_attempts_user_id'), ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_login_attempts_user_id'))
    op.drop_table('user_login_attempts')
    # ### end Alembic commands ###
